# Generated by Django 4.0.1 on 2022-04-06 05:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('number', models.PositiveIntegerField()),
                ('password', models.CharField(default='', max_length=15)),
                ('confirmPassword', models.CharField(default='', max_length=15)),
                ('link', models.CharField(default='', max_length=55)),
                ('payment_due_date', models.DateField(default=datetime.datetime(2022, 4, 21, 5, 51, 37, 491567))),
                ('percentage', models.PositiveIntegerField(default=0)),
                ('totalNoOfReferrals', models.CharField(default=0, max_length=100)),
                ('amount', models.CharField(default=0, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PrsignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('number', models.PositiveIntegerField()),
                ('password', models.CharField(default='', max_length=15)),
                ('confirmPassword', models.CharField(default='', max_length=15)),
                ('link', models.CharField(default='', max_length=55)),
                ('recommend_by', models.CharField(default='', max_length=30)),
                ('payment_due_date', models.DateField(default=datetime.datetime(2022, 4, 21, 5, 51, 37, 491240))),
                ('ispaid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Offerings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(default=0, max_length=100)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('tier1', models.PositiveIntegerField(default=0)),
                ('tier2', models.PositiveIntegerField(default=0)),
                ('tier3', models.PositiveIntegerField(default=0)),
                ('percentage1', models.PositiveIntegerField(default=10)),
                ('percentage2', models.PositiveIntegerField(default=20)),
                ('percentage3', models.PositiveIntegerField(default=30)),
                ('CA', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CA.casignup')),
            ],
        ),
        migrations.AddField(
            model_name='casignup',
            name='subuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CA.prsignup'),
        ),
    ]
