# Generated by Django 4.0.3 on 2022-04-06 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0002_remove_casignup_subuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerings',
            old_name='tier1',
            new_name='percentage',
        ),
        migrations.RenameField(
            model_name='offerings',
            old_name='tier2',
            new_name='tierNo',
        ),
        migrations.RemoveField(
            model_name='casignup',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='casignup',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='offerings',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='offerings',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='offerings',
            name='percentage1',
        ),
        migrations.RemoveField(
            model_name='offerings',
            name='percentage2',
        ),
        migrations.RemoveField(
            model_name='offerings',
            name='percentage3',
        ),
        migrations.RemoveField(
            model_name='offerings',
            name='tier3',
        ),
        migrations.AddField(
            model_name='casignup',
            name='created_by',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='offerings',
            name='isPaymentRecieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offerings',
            name='joiningDate',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='offerings',
            name='monthlyAmount',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='offerings',
            name='paymentRecievedDate',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='offerings',
            name='pendingAmount',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='offerings',
            name='tierName',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='offerings',
            name='totalAmount',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='casignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 21, 12, 27, 10, 924230)),
        ),
        migrations.AlterField(
            model_name='prsignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 21, 12, 27, 10, 923728)),
        ),
    ]
