# Generated by Django 4.0.3 on 2022-04-07 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0004_alter_casignup_payment_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casignup',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='casignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 22, 4, 8, 50, 233584)),
        ),
        migrations.AlterField(
            model_name='prsignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 22, 4, 8, 50, 233268)),
        ),
    ]
