# Generated by Django 4.0.3 on 2022-04-07 06:32

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0005_casignup_address_alter_casignup_payment_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 22, 6, 32, 21, 171370)),
        ),
        migrations.AlterField(
            model_name='casignup',
            name='totalNoOfReferrals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offerings',
            name='joiningDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='prsignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 22, 6, 32, 21, 170958)),
        ),
    ]
