# Generated by Django 4.0.3 on 2022-04-08 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0008_rename_current_refereal_offerings_noreferals_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 23, 5, 5, 21, 670590)),
        ),
        migrations.AlterField(
            model_name='offerings',
            name='monthlyAmount',
            field=models.PositiveIntegerField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='offerings',
            name='pendingAmount',
            field=models.PositiveIntegerField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='offerings',
            name='totalAmount',
            field=models.PositiveIntegerField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='prsignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 23, 5, 5, 21, 670114)),
        ),
    ]
